# Generated by Django 5.2.17 on 2026-09-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productvariant_stock_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id'], 'verbose_name': 'Variant', 'verbose_name_plural': 'Variantlar'},
        ),
    ]
