# Generated by Django 5.2 on 2026-09-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ism-familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('delivered', 'Yetkazilgan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=12, verbose_name='Holati')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd (yetkazilganda)'), ('terminal', 'Terminal'), ('payme', 'Payme'), ('click', 'Click')], default='cash', max_length=10, verbose_name="To'lov usuli")),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('paid', "To'langan"), ('refunded', 'Qaytarilgan')], default='unpaid', max_length=10, verbose_name="To'lov holati")),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Jami (so'm)")),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birlik narxi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('variant_name', models.CharField(blank=True, max_length=120, verbose_name='Variant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma qatori',
                'verbose_name_plural': 'Buyurtma qatorlari',
            },
        ),
    ]
