# Generated by Django 5.2 on 2026-09-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Yetkazish manzili'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_reserved',
            field=models.BooleanField(default=False, verbose_name='Stokdan ayirilgan'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Oxirgi manzil'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon'),
        ),
    ]
